/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/miniskeleton-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SK_Femur_MI_Skeleton01_LP_0.geometry}
        material={materials.MI_Skeleton01_LP}
        position={[-0.038, 0.891, 0.226]}
        rotation={[-1.572, -0.012, 0.003]}
      />
    </group>
  )
}

useGLTF.preload('/miniskeleton-v1.glb')