/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mini skeleton.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.038, 0.082, 0.138]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.001, 116.62, 8.863]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.106, 0, -0.133]} rotation={[-0.001, -0.012, 0.003]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.SK_Femur_MI_Skeleton01_LP_0.geometry}
                material={materials.MI_Skeleton01_LP}
                position={[-0.109, 0.001, -0.223]}
              />
              <group position={[-0.023, 0.003, -0.498]} rotation={[0.005, 0.012, -0.003]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Fibula_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[-0.089, 0.035, -0.219]}
                />
              </group>
              <group
                position={[-0.004, -0.039, -0.5]}
                rotation={[0.265, -0.001, -0.003]}
                scale={0.946}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Patella_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[-0.115, -0.001, -0.001]}
                />
              </group>
              <group position={[-0.023, 0.003, -0.498]} rotation={[0.004, 0.012, -0.003]}>
                <group position={[0.025, -0.038, -0.506]} rotation={[-0.033, 0, 0]}>
                  <group position={[-0.022, -0.017, 0.009]} rotation={[0.03, 0, 0]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Metatarsal_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.092, -0.064, -0.014]}
                    />
                  </group>
                  <group position={[-0.004, -0.009, 0.025]} rotation={[-0.012, 0.007, 0.005]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Metatarsal001_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.11, -0.066, -0.028]}
                    />
                  </group>
                  <group position={[0.009, -0.004, 0.02]} rotation={[0.159, -0.066, -0.045]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Metatarsal002_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.121, -0.071, -0.007]}
                    />
                  </group>
                  <group position={[0.02, 0.007, 0.009]} rotation={[0.056, -0.097, -0.009]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Metatarsal003_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.135, -0.064, 0]}
                    />
                  </group>
                  <group position={[0.032, 0.021, -0.003]} rotation={[0.03, 0, 0]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Metatarsal004_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.146, -0.049, -0.008]}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SK_Tarsal_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.114, 0.054, 0.023]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Tibia_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[-0.089, 0.016, -0.226]}
                />
              </group>
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SK_Pelvis_MI_Skeleton01_LP_0.geometry}
              material={materials.MI_Skeleton01_LP}
              position={[0.004, 0.023, -0.08]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SK_Pelvis_MI_Skeleton01_LP_0001.geometry}
              material={materials.MI_Skeleton01_LP}
              position={[-0.039, 0.026, -0.109]}
            />
            <group position={[0, 0.004, 0.002]}>
              <group position={[-0.003, -0.038, 0.79]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Cranium_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[0.005, -0.019, -0.005]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Cranium_MI_Skeleton01_LP_0001.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[-0.015, -0.051, -0.005]}
                />
                <group position={[0.021, -0.091, -0.065]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_canines003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.021, -0.002, 0]}
                  />
                </group>
                <group position={[0.004, -0.097, -0.064]} rotation={[0, -0.047, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_incisors01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.004, 0, -0.002]}
                  />
                </group>
                <group position={[0.014, -0.095, -0.065]} rotation={[1.515, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_incisors02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.014, 0.001, 0]}
                  />
                </group>
                <group position={[0.034, -0.066, -0.065]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_molars01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.034, -0.001, 0]}
                  />
                </group>
                <group position={[0.036, -0.055, -0.063]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_molars02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.036, -0.002, 0]}
                  />
                </group>
                <group position={[0.036, -0.045, -0.063]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_molars03003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.036, -0.001, 0]}
                  />
                </group>
                <group position={[0.026, -0.084, -0.068]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_premolars01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.026, -0.001, 0]}
                  />
                </group>
                <group position={[0.03, -0.074, -0.065]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Upper_premolars02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.03, -0.001, 0]}
                  />
                </group>
                <group position={[0.015, -0.086, -0.098]} rotation={[1.807, -0.253, 0.03]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_canines003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.013, 0.012, 0.006]}
                  />
                </group>
                <group position={[0.002, -0.088, -0.101]} rotation={[1.888, 0.034, -0.041]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_incisors01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.003, 0.012, 0.002]}
                  />
                </group>
                <group position={[0.007, -0.088, -0.099]} rotation={[1.83, -0.268, -0.152]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_incisors02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.008, 0.009, 0.004]}
                  />
                </group>
                <group position={[0.029, -0.068, -0.087]} rotation={[1.618, 0.057, -0.006]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_molars01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.029, 0.001, -0.002]}
                  />
                </group>
                <group position={[0.033, -0.056, -0.086]} rotation={[1.58, 0.031, 0.096]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_molars02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.033, 0.005, -0.001]}
                  />
                </group>
                <group position={[0.035, -0.047, -0.082]} rotation={[1.484, 0.016, 0.045]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_molars03003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.035, 0.002, 0]}
                  />
                </group>
                <group position={[0.019, -0.084, -0.088]} rotation={[1.778, -0.18, -0.16]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_premolars01003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.019, -0.003, 0.004]}
                  />
                </group>
                <group position={[0.025, -0.077, -0.089]} rotation={[1.577, 0.045, -0.097]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lower_premolars02003_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.025, -0.001, -0.001]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Mandible_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[0, -0.046, -0.09]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.SK_Spine_MI_Skeleton01_LP_0.geometry}
                material={materials.MI_Skeleton01_LP}
                position={[-0.005, 0.01, 0.415]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.SK_Spine_MI_Skeleton01_LP_0001.geometry}
                material={materials.MI_Skeleton01_LP}
                position={[0.009, 0.018, 0.418]}
              />
              <group position={[0.015, -0.085, 0.558]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.SK_Clavicle_MI_Skeleton01_LP_0.geometry}
                  material={materials.MI_Skeleton01_LP}
                  position={[-0.018, 0.008, 0.002]}
                />
                <group position={[0.188, -0.01, -0.022]} rotation={[0.264, -0.116, 0.031]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SK_Humerus_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.227, -0.014, -0.158]}
                  />
                  <group position={[0.017, -0.071, -0.378]} rotation={[-0.262, 0.145, 0]}>
                    <group position={[0.023, 0.004, -0.315]} rotation={[0, -0.025, 0.54]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.SK_Carpals_MI_Skeleton01_LP_0.geometry}
                        material={materials.MI_Skeleton01_LP}
                        position={[-0.241, 0.145, 0]}
                      />
                      <group position={[-0.045, -0.006, -0.026]} rotation={[0, 0, 0.239]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.SK_Metacarpal_MI_Skeleton01_LP_0.geometry}
                          material={materials.MI_Skeleton01_LP}
                          position={[-0.175, 0.17, -0.005]}
                        />
                        <group position={[-0.021, 0.007, -0.044]} rotation={[0, 0, -0.78]}>
                          <group position={[-0.011, -0.001, -0.029]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.SK_Phalange005_MI_Skeleton01_LP_0.geometry}
                              material={materials.MI_Skeleton01_LP}
                              position={[-0.215, 0.001, -0.005]}
                            />
                          </group>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.SK_Phalange_MI_Skeleton01_LP_0.geometry}
                            material={materials.MI_Skeleton01_LP}
                            position={[-0.224, 0, -0.005]}
                          />
                        </group>
                      </group>
                      <group
                        position={[-0.022, -0.016, -0.045]}
                        rotation={[-0.253, -0.006, -0.526]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.SK_Metacarpal001_MI_Skeleton01_LP_0.geometry}
                          material={materials.MI_Skeleton01_LP}
                          position={[-0.268, 0, 0.026]}
                        />
                        <group position={[-0.019, 0.006, -0.067]} rotation={[0.217, 0.131, -0.03]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.SK_Phalange001_MI_Skeleton01_LP_0.geometry}
                            material={materials.MI_Skeleton01_LP}
                            position={[-0.261, 0.001, -0.004]}
                          />
                          <group position={[0, 0.01, -0.041]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.SK_Phalange006_MI_Skeleton01_LP_0.geometry}
                              material={materials.MI_Skeleton01_LP}
                              position={[-0.26, 0.002, -0.003]}
                            />
                            <group position={[0.003, 0.013, -0.016]} rotation={[0, 0, 0.193]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.SK_Phalange010_MI_Skeleton01_LP_0.geometry}
                                material={materials.MI_Skeleton01_LP}
                                position={[-0.256, 0.054, -0.006]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group position={[0, -0.017, -0.059]} rotation={[0, 0, -0.54]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.SK_Metacarpal002_MI_Skeleton01_LP_0.geometry}
                          material={materials.MI_Skeleton01_LP}
                          position={[-0.291, 0.001, 0.001]}
                        />
                        <group position={[0.003, 0.001, -0.061]} rotation={[0.11, -0.05, 0.662]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.SK_Phalange002_MI_Skeleton01_LP_0.geometry}
                            material={materials.MI_Skeleton01_LP}
                            position={[-0.231, 0.18, 0.009]}
                          />
                          <group position={[0, 0.005, -0.049]} rotation={[-0.056, 0.107, 0.112]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.SK_Phalange007_MI_Skeleton01_LP_0.geometry}
                              material={materials.MI_Skeleton01_LP}
                              position={[-0.211, 0.205, -0.004]}
                            />
                            <group
                              position={[0.006, 0.008, -0.021]}
                              rotation={[0.241, 0.032, -0.083]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.SK_Phalange011_MI_Skeleton01_LP_0.geometry}
                                material={materials.MI_Skeleton01_LP}
                                position={[-0.22, 0.178, -0.063]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group position={[0.024, -0.01, -0.041]} rotation={[0.044, -0.139, -0.499]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.SK_Metacarpal003_MI_Skeleton01_LP_0.geometry}
                          material={materials.MI_Skeleton01_LP}
                          position={[-0.306, 0.012, 0.022]}
                        />
                        <group position={[0.007, -0.006, -0.061]} rotation={[-0.169, 0.151, 0.735]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.SK_Phalange003_MI_Skeleton01_LP_0.geometry}
                            material={materials.MI_Skeleton01_LP}
                            position={[-0.233, 0.22, -0.021]}
                          />
                          <group
                            position={[0.005, 0.004, -0.044]}
                            rotation={[0.013, -0.079, 0.175]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.SK_Phalange008_MI_Skeleton01_LP_0.geometry}
                              material={materials.MI_Skeleton01_LP}
                              position={[-0.186, 0.256, -0.004]}
                            />
                            <group
                              position={[0.005, 0.005, -0.023]}
                              rotation={[0.11, 0.189, -0.195]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.SK_Phalange012_MI_Skeleton01_LP_0.geometry}
                                material={materials.MI_Skeleton01_LP}
                                position={[-0.225, 0.217, -0.07]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group position={[0.029, 0.01, -0.01]} rotation={[0.058, -0.179, -0.485]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.SK_Metacarpal004_MI_Skeleton01_LP_0.geometry}
                          material={materials.MI_Skeleton01_LP}
                          position={[-0.302, 0.01, 0.014]}
                        />
                        <group position={[0.022, -0.012, -0.067]} rotation={[-0.135, 0.13, 1.012]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.SK_Phalange004_MI_Skeleton01_LP_0.geometry}
                            material={materials.MI_Skeleton01_LP}
                            position={[-0.166, 0.287, -0.004]}
                          />
                          <group position={[0.001, -0.002, -0.037]} rotation={[0, 0, -0.019]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.SK_Phalange009_MI_Skeleton01_LP_0.geometry}
                              material={materials.MI_Skeleton01_LP}
                              position={[-0.17, 0.288, -0.003]}
                            />
                            <group position={[0.002, 0.004, -0.017]} rotation={[0, 0, -0.037]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.SK_Phalange013_MI_Skeleton01_LP_0.geometry}
                                material={materials.MI_Skeleton01_LP}
                                position={[-0.178, 0.277, -0.006]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Radius_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.263, 0.004, -0.149]}
                    />
                  </group>
                  <group position={[-0.002, -0.06, -0.383]} rotation={[-0.255, 0.133, 1.457]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.SK_Ulna_MI_Skeleton01_LP_0.geometry}
                      material={materials.MI_Skeleton01_LP}
                      position={[-0.021, 0.248, -0.114]}
                    />
                  </group>
                </group>
                <group position={[-0.015, 0.085, -0.556]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SK_Scapula_MI_Skeleton01_LP_0.geometry}
                    material={materials.MI_Skeleton01_LP}
                    position={[-0.003, -0.037, 0.513]}
                  />
                </group>
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.SK_RibCage_MI_Skeleton01_LP_0.geometry}
                material={materials.MI_Skeleton01_LP}
                position={[0.002, -0.064, 0.407]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.SK_RibCage_MI_Skeleton01_LP_0001.geometry}
                material={materials.MI_Skeleton01_LP}
                position={[-0.026, -0.075, 0.472]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mini skeleton.glb')